name: Build

on: push

jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Run build
        run: npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
         commit_message: "automated: build"
         file_pattern: "."